server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /gestionale-2 {
    return 301 /gestionale-2/;
  }

  location /gestionale-2/ {
    try_files $uri $uri/ /gestionale-2/index.html;
  }

  location / {
    return 404;
  }
}
